### ISSUE TITLE
Better support with Spotify? (And less ram usage if possible?)

### ISSUE THREAD

**Issue by ghost** [DanielVolt/Velox-Issue-Tracker#6]
I was wondering if it was possible for you guys to make Spotify look a bit more fluent (especially for the small widget) on the springboard, like having the album artwork take up the whole widget display, as well as having better responsiveness with the buttons and not showing the icon “layer on top of” the widget when closing. (Theres also a slight bug were the tweak will display no media output when turning a page momentarily).

Video: https://streamable.com/i6yfl

I was also wondering if you guys planned to improve RAM management going down the road, as the tweak seems to drastically reduce the amount I have available.

Nonetheless, great work so far, and I hope to see this tweak get better with age

**Comment by DanielVolt** [comment]
We're on it, we have multiple UI's created for Spotify and will be enabled in Future updates.

As for RAM management we're for sure re-implementing certain aspects of Velox so it works flawlessly

**Comment by DanielVolt** [comment]
RAM has been optimized in Velox 1.1
